name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # またはデプロイ対象のブランチ名

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public  # HTMLファイルがあるディレクトリ
          name: github-pages-site  # ← 重複しない一意な名前に変更

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-site  # ← 上と一致させる
